---
- name: Create /usr/local/bin
  ansible.builtin.file:
    path: "/usr/local/bin"
    state: directory
    mode: "0755"
  become: true

- name: Install neovim
  ansible.builtin.get_url:
    url: >-
      https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux-{{ neovim_arch }}.appimage
    dest: /usr/local/bin/nvim
    mode: +x
  vars:
    neovim_arch: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'x86_64' }}"
  become: true
  when:
    - ansible_facts["system"] == "Linux"
    - ansible_facts["architecture"] in ["x86_64", "aarch64"]
- name: Install ripgrep
  block:
    - name: Download
      ansible.builtin.get_url:
        url: >-
          https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/{{ ripgrep_archive }}.tar.gz
        dest: "/tmp/{{ ripgrep_archive }}.tar.gz"
      when:
        - ansible_facts["system"] == "Linux"
        - ansible_facts["architecture"] in ["x86_64", "aarch64"]
    - name: Unarchive
      ansible.builtin.unarchive:
        src: "/tmp/{{ ripgrep_archive }}.tar.gz"
        dest: "/tmp"
        remote_src: true
    - name: Copy
      ansible.builtin.copy:
        src: "/tmp/{{ ripgrep_archive }}/rg"
        dest: "/usr/local/bin/rg"
        remote_src: true
        mode: '0755'
  vars:
    ripgrep_arch: >-
      {{ 'aarch64-unknown-linux-gnu' if ansible_facts['architecture'] == 'aarch64' else 'x86_64-unknown-linux-musl' }}
    ripgrep_archive: "ripgrep-{{ ripgrep_version }}-{{ ripgrep_arch }}"
  when:
    - ansible_facts["system"] == "Linux"
    - ansible_facts["architecture"] in ["x86_64", "aarch64"]
  become: true
