---
- name: Create /usr/local/bin
  ansible.builtin.file:
    path: "/usr/local/bin"
    state: directory
    mode: "0755"
  become: true

- name: Install neovim
  ansible.builtin.get_url:
    url: >-
      https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim-linux-{{ 'arm64' if ansible_facts["architecture"] == 'aarch64' else 'x86_64' }}.appimage
    dest: /usr/local/bin/nvim
    mode: +x
  become: true
  when:
    - ansible_facts["system"] == "Linux"
    - ansible_facts["architecture"] in ["x86_64", "aarch64"]
- name: Install ripgrep
  block:
    - name: Download
      ansible.builtin.get_url:
        url: >-
          https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep-{{ ripgrep_version }}-{{ 'aarch64-unknown-linux-gnu' if ansible_facts["architecture"] == 'aarch64' else 'x86_64-unknown-linux-musl' }}.tar.gz
        dest: "/tmp/ripgrep-{{ ripgrep_version }}-{{ 'aarch64-unknown-linux-gnu' if ansible_facts['architecture'] == 'aarch64' else 'x86_64-unknown-linux-musl' }}.tar.gz"
      when:
        - ansible_facts["system"] == "Linux"
        - ansible_facts["architecture"] in ["x86_64", "aarch64"]
    - name: Unarchive
      ansible.builtin.unarchive:
        src: "/tmp/ripgrep-{{ ripgrep_version }}-{{ 'aarch64-unknown-linux-gnu' if ansible_facts['architecture'] == 'aarch64' else 'x86_64-unknown-linux-musl' }}.tar.gz"
        dest: "/tmp"
        remote_src: true
    - name: Copy
      ansible.builtin.copy:
        src: "/tmp/ripgrep-{{ ripgrep_version }}-{{ 'aarch64-unknown-linux-gnu' if ansible_facts['architecture'] == 'aarch64' else 'x86_64-unknown-linux-musl' }}/rg"
        dest: "/usr/local/bin/rg"
        remote_src: true
        mode: 755
  when:
    - ansible_facts["system"] == "Linux"
    - ansible_facts["architecture"] in ["x86_64", "aarch64"]
  become: true
