---
- name: Install package via apt
  ansible.builtin.apt:
    state: present
    # state: latest # 更新する場合はこちらにする
    update_cache: true
    pkg:
      - build-essential
      - ceph-common
      - libfuse-dev
      - python3-venv
